name: Discord Notification on Push

on:
  push:
    branches:
      - main
      - dev-sebastian

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Se ha realizado un push en una rama del repositorio."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
