name: first pipeline

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Revisar repositorio
      run: echo "Test DevOps"

    - name: Analizar repositorio
      run: ls -la